config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      get 'garage', to: "cars#garage"
    end

    member do
      get :toggle, to: "cars#rental_toggle", as: :toggle
    end

    resources :bookings, only: [:create, :destroy]
  end
  resources :bookings, only: [:index] do
    collection do
      get 'garage_bookings', to: "bookings#garage_bookings"
    end
  end
  resources :ratings, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :driver, class_name: "User"
  has_many :ratings, dependent: :destroy

  validates :purpose, inclusion: { in: ["Competition", "Showing", "Tourism", "Wedding", "Other Event"]}
  validates :bk_start, presence: true, allow_blank: false
  validates :bk_end, presence: true, allow_blank: false
  validates :bk_price, presence: true, allow_blank: false, numericality: true
  # validate :valid_dates

  def valid_dates
    return unless bk_start && bk_end

    if bk_start < Date.today
      errors.add("Start date has to be in the future")
    elsif bk_end < Date.today
      errors.add("End date has to be in the future")
    elsif bk_end <= bk_start
      errors.add("End date must be greater than start date")
    end
  end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :bookings
  has_many :ratings, through: :bookings

  validates :brand, presence: true, allow_blank: false
  validates :model, presence: true, allow_blank: false
  validates :car_type, presence: true, inclusion: { in: ["Convertible", "Coupe", "Hatchback", "Luxury", "SUV", "Sedan", "Sports", "Truck", "Van", "Wagon"] }
  validates :fuel_type, presence: true, inclusion: { in: ["Bio-diesel", "Diesel", "Ethanol", "Gasoline", "Natural Gas", "Propane"] }
  validates :car_photo, presence: true, allow_blank: false
  validates :year, presence: true, allow_blank: false, numericality: { only_integer: true }
  validates :mileage, presence: true, allow_blank: false, numericality: { only_integer: true }
  validates :price, presence: true, allow_blank: false, numericality: true

  include PgSearch
  pg_search_scope :search_by_all,
                  against: [:brand, :model],
                  using: {
                    tsearch: { prefix: true }
                  }

  pg_search_scope :global_search,
                  against: [:brand, :model],
                  associated_against: {
                    owner: [:address, :name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :booking

  validates :rt_fun, presence: true, allow_blank: false, inclusion: { in: (1..5).to_a, message: "Rating must be between 1 and 5." }
  validates :rt_condition, presence: true, allow_blank: false, inclusion: { in: (1..5).to_a, message: "Rating must be between 1 and 5." }
  validates :rt_performance, presence: true, allow_blank: false, inclusion: { in: (1..5).to_a, message: "Rating must be between 1 and 5." }
  validates :rt_owner, presence: true, allow_blank: false, inclusion: { in: (1..5).to_a, message: "Rating must be between 1 and 5." }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, foreign_key: :owner_id, dependent: :destroy
  has_many :ratings, through: :cars, foreign_key: :owner_id, dependent: :destroy
  has_many :bookings, foreign_key: :driver_id, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  # validates :name, presence: true, allow_blank: false
  # validates :address, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :photo])
  end

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Where are do you think you were going, beautiful beast?"
    redirect_to(root_path)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_car, only: %i[create]

  def index
    @bookings = policy_scope(Booking).all
  end

  def garage_bookings
    authorize Booking
    @cars = Car.where(owner: current_user)
    @bookings = policy_scope(Booking).where(car: @cars)
  end

  # def b_index_user
  #   @bookings = policy_scope(Booking).where(driver: current_user)
  # end

  # def b_index_owner
  #   @cars = Car.where(owner: current_user)
  #   @bookings = policy_scope(Booking).where(car: @cars)
  # end

  # def b_index_car
  #   # Ruby directly on cars/show.html.erb
  #   # Missing the connection to @car
  #   @bookings = policy_scope(Booking).where(car_id: @car)
  #   #@bookings = policy_scope(Booking).where(car_id: 12)
  # end

  def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.driver = current_user
    @booking.bk_price = @car.price
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      flash[:alert] = @booking.errors.full_messages.join(', ')
      redirect_to @car
    end
  end

  def destroy # only if status "created"
    authorize @booking
  end

  private

  def find_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:car_id, :driver_id, :purpose,
                                    :status, :bk_start, :bk_end,
                                    :bk_price)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update rental_toggle]

  def index
    if params[:query].present?
      @cars = policy_scope(Car).where(for_rental: true).order(:brand).global_search(params[:query])
    else
      @cars = policy_scope(Car).where(for_rental: true).order(:brand)
    end
    @cars = @cars.reject { |car| car.owner == current_user }
  end

  def garage
    authorize Car
    @cars = policy_scope(Car).where(owner: current_user).order(:brand)
  end

  def rental_toggle
    authorize @car
    @car.for_rental = !@car.for_rental
    @car.save

    redirect_to garage_cars_path
  end

  def show
    authorize @car
    @booking = Booking.new
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.owner = current_user
    authorize @car
    if @car.save
      redirect_to @car
    else
      :new
    end
  end

  def edit
    authorize @car
  end

  def update
    authorize @car
    if @car.update(car_params)
      redirect_to @car
    else
      :edit
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :model,
                                :car_type, :fuel_type, :description,
                                :car_photo, :year, :mileage,
                                :price, :date_start, :date_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    authorize @rating
  end

  def create
    authorize @rating
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/garage_bookings.html.erb
<div class="container .div-car-bookings">

<!-- <h2><%#= current_user.name %>'s dream car rides..</h2> -->

  <div class="row garage-buttons">
    <%= link_to "Add Car", new_car_path, class: "btn btn-primary" %>
    <%= link_to "Show Cars", garage_cars_path, class: "btn btn-primary" %>
  </div>

<!-- *************** TABLEAU ***************************** -->
  <% i = 0 %>
  <% sum = 0 %>
  <% days = 0 %>
  <% sdays = 0 %>

  <% @bookings.each do |booking| %>
    <% i += 1 %>
    <% days = (booking.bk_end - booking.bk_start).to_i %>
    <% sdays += days %>
    <% sum += days * booking.car.price %>
    <% end %>

   <tr>
    <p style="text-align:center; color: gray">
      <td> Rentals: <strong><%= i %></strong> | </td>
      <td> Days: <strong><%= sdays %></strong> | </td>
      <td> Revenues: <strong><%=number_to_currency((sum), precision: 0, unit: "€", separator: ",", delimiter: ".", format: "%n %u")%></strong></td>
    </p>
   </tr>

<!-- <h6  style="text-align:right">for detailed memmories check each review..</h6>
 -->
<!-- *************** HEADER ***************************** -->


  <div class="row">

    <ul class="flex-container flex-start table-header">
      <li class="flex-item col-1"></li>
      <li class="flex-item col-2">Brand</li>
      <li class="flex-item col-3">Driver</li>
      <li class="flex-item col-4">Start Date</li>
      <li class="flex-item col-4">Days</li>
      <li class="flex-item col-5">Price</li>
      <li class="flex-item col-6">Rating</li>
      <!--  <li class="flex-item col-7">Review</li> -->
    </ul>

    <% @bookings.order('bk_start DESC').each do |booking| %>

    <ul class="flex-container flex-start table-row">
      <li class="flex-item col-1">
        <div style="background: url(<%= image_path booking.car.car_photo %>) no-repeat center center; background-size: cover; height: 70px; border-radius: 5px"></div>
        </li>
      <li class="flex-item col-2"><%= booking.car.brand %></li>
      <li class="flex-item col-3"><%= booking.driver.name %></li>
      <li class="flex-item col-4"><%= booking.bk_start %></li>
      <li class="flex-item col-4"><%= days = (booking.bk_end - booking.bk_start).to_i %></li>
      <li class="flex-item col-5">
        <%=number_to_currency((booking.car.price * days), precision: 0, unit: "€", separator: ",", delimiter: ".", format: "%n %u")%>
      </li>
      <li class="flex-item col-6">
        <div class="rating garage-rating">
            <% sum_rat = booking.ratings.sum(:rt_fun) + booking.ratings.sum(:rt_condition) + booking.ratings.sum(:rt_performance) + booking.ratings.sum(:rt_owner) %>
            <% count_rat = booking.ratings.count %>

              <% if count_rat.zero? %>

              <% if booking.bk_start <= Date.today %>
                <p style="color: #18A999; font-weight: bold">Ongoing</p>

              <% else booking.bk_start > Date.today %>
                <p style="color: #1D84B5; font-weight: bold">Planned</p>

              <% end %>

            <% else %>

              <% rat_calc = (sum_rat / (count_rat * 4).to_f).round(0) %>
              <p>
                <% (rat_calc).times do %><i class="fas fa-circle fa-sm" style="margin-top: 0px"></i><% end %><% (5 - rat_calc).times do %><i class="far fa-circle fa-sm"></i><% end %>
              </p>

            <% end %>
          </div>
      </li>
<!--       <li class="flex-item col-7 last-li">
        <a href="#" onclick="toggle_visibility('review');">
          <i class="fas fa-file-alt" style="font-size: 30px"></i>
        </a>
      </li> -->
    </ul>

    <!-- hidden div -->
<!--      <ul id="review" style="display:none;" class="flex-container flex-start table-row review-ul">
          <li class="flex-item">
            <div>
              <%#= booking.car.description %>
            </div>
          </li>
      </ul> -->
    <% end %>


  </div>

</div>

app/views/bookings/index.html.erb
<div class="container .div-car-bookings">

<!-- <h2><%#= current_user.name %>'s dream car rides..</h2> -->

  <div class="row garage-buttons">
    <%#= link_to "Add Car", new_car_path, class: "btn btn-primary" %>
    <%#= link_to "Show Cars", garage_cars_path, class: "btn btn-primary" %>
  </div>

<!-- *************** TABLEAU ***************************** -->
  <% i = 0 %>
  <% sum = 0 %>
  <% days = 0 %>
  <% sdays = 0 %>

  <% @bookings.where(driver: current_user).each do |booking| %>
    <% i += 1 %>
    <% days = (booking.bk_end - booking.bk_start).to_i %>
    <% sdays += days %>
    <% sum += days * booking.car.price %>
    <% end %>

   <tr>
    <p style="text-align:center; color: gray">
      <td> Rentals: <strong><%= i %></strong> | </td>
      <td> Days: <strong><%= sdays %></strong> | </td>
      <td> Expenses: <strong><%=number_to_currency((sum), precision: 0, unit: "€", separator: ",", delimiter: ".", format: "%n %u")%></strong></td>
    </p>
   </tr>

<!-- <h6  style="text-align:right">for detailed memmories check each review..</h6>
 -->
<!-- *************** HEADER ***************************** -->


  <div class="row">

    <ul class="flex-container flex-start table-header">
      <li class="flex-item col-1"></li>
      <li class="flex-item col-2">Brand</li>
      <li class="flex-item col-3">Owner</li>
      <li class="flex-item col-4">Start Date</li>
      <li class="flex-item col-4">Days</li>
      <li class="flex-item col-5">Price</li>
      <li class="flex-item col-6">Rating</li>
      <!--  <li class="flex-item col-7">Review</li> -->
    </ul>

    <% @bookings.where(driver: current_user).order('bk_start DESC').each do |booking| %>

    <ul class="flex-container flex-start table-row">
      <li class="flex-item col-1">
        <div style="background: url(<%= image_path booking.car.car_photo %>) no-repeat center center; background-size: cover; height: 70px; border-radius: 5px"></div>
        </li>
      <li class="flex-item col-2"><%= booking.car.brand %></li>
      <li class="flex-item col-3"><%= booking.car.owner.name %></li>
      <li class="flex-item col-4"><%= booking.bk_start %></li>
      <li class="flex-item col-4"><%= days = (booking.bk_end - booking.bk_start).to_i %></li>
      <li class="flex-item col-5">
        <%=number_to_currency((booking.car.price * days), precision: 0, unit: "€", separator: ",", delimiter: ".", format: "%n %u")%>
      </li>
      <li class="flex-item col-6">
        <div class="rating garage-rating">
            <% sum_rat = booking.ratings.sum(:rt_fun) + booking.ratings.sum(:rt_condition) + booking.ratings.sum(:rt_performance) + booking.ratings.sum(:rt_owner) %>
            <% count_rat = booking.ratings.count %>

              <% if count_rat.zero? %>

              <% if booking.bk_start <= Date.today %>
                <p style="color: #18A999; font-weight: bold">Ongoing</p>

              <% else booking.bk_start > Date.today %>
                <p style="color: #1D84B5; font-weight: bold">Planned</p>

              <% end %>

            <% else %>

              <% rat_calc = (sum_rat / (count_rat * 4).to_f).round(0) %>
              <p>
                <% (rat_calc).times do %><i class="fas fa-circle fa-sm" style="margin-top: 0px"></i><% end %><% (5 - rat_calc).times do %><i class="far fa-circle fa-sm"></i><% end %>
              </p>

            <% end %>
          </div>
      </li>
<!--       <li class="flex-item col-7 last-li">
        <a href="#" onclick="toggle_visibility('review');">
          <i class="fas fa-file-alt" style="font-size: 30px"></i>
        </a>
      </li> -->
    </ul>

    <!-- hidden div -->
<!--      <ul id="review" style="display:none;" class="flex-container flex-start table-row review-ul">
          <li class="flex-item">
            <div>
              <%#= booking.car.description %>
            </div>
          </li>
      </ul> -->
    <% end %>


  </div>

</div>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

app/views/cars/garage.html.erb
<div class="container">

  <div class="row garage-buttons">
    <%= link_to "Add Car", new_car_path, class: "btn btn-primary" %>
    <%= link_to "Show Bookings", garage_bookings_bookings_path, class: "btn btn-primary" %>
  </div>

  <div class="row">

    <% @cars.each do |car| %>
      <div class="card-container col-xs-12 col-sm-6 col-md-4">
        <div class="car-card">

          <div class="car-background" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.2)), url(<%= car.car_photo %>); background-size: cover; background-repeat: no-repeat; background-position: center; height: 150px">


            <div class="car-card-header">
              <h3><%= car.brand %></h3>
              <p><%= car.model %></p>
            </div>
          </div>

          <div class="car-card-price">
            <p><%= car.price.to_i %></p>
            <p class="smaller">€/day</p>
          </div>

          <div class="car-card-footer-left">
            <div class="ratings">

              <% sum_rat = car.ratings.sum(:rt_fun) + car.ratings.sum(:rt_condition) + car.ratings.sum(:rt_performance) + car.ratings.sum(:rt_owner) %>

              <% count_rat = car.ratings.count %>

              <% rat_calc = count_rat.zero? ? 0 : (sum_rat / (count_rat * 4).to_f).ceil %>

              <% if rat_calc.zero? %>
                <p><strong>New car!</strong></p>

              <% else %>
                <% (rat_calc).times do %>
                  <i class="fas fa-circle"></i>
                <% end %>
                <% (5 - rat_calc).times do %>
                  <i class="far fa-circle"></i>
                <% end %>
              <% end %>

            </div>
            <p class="garage-actions">
              <i class="fas fa-edit fa-lg"><a href="#"></a></i>
              <% if car.for_rental %>
                <i class="fas fa-check-circle fa-lg"><a href=<%= "#{car.id}/toggle" %>></a></i>
              <% else %>
                <i class="fas fa-ban fa-lg" style="color: red"><a href=<%= "#{car.id}/toggle" %>></a></i>
              <% end %>
            </p>
          </div>

          <div class="car-card-footer-right">
            <p><i class="fas fa-industry"></i> <%= car.year %></p>
            <p><i class="fas fa-car-crash"></i> <%= number_with_delimiter(car.mileage, :delimiter => '.') %> km</p>
          </div>

          <%= link_to "", car_path(car) %>

        </div>
      </div>
  <% end %>

  </div>
</div>

app/views/cars/index.html.erb
<div class="container">

  <div class="row">
    <%= form_tag cars_path, class: "search-form", method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a Karr by brand, model, owner or location"
      %>
      <%= button_tag(type: 'submit', class: "btn btn-search") do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>

  <div class="row">

    <% @cars.each do |car| %>
      <div class="card-container col-xs-12 col-sm-6 col-md-4">
        <div class="car-card">

          <div class="car-background" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.2)), url(<%= car.car_photo %>); background-size: cover; background-repeat: no-repeat; background-position: center; height: 150px">
            <div class="car-card-header">
              <h3><%= car.brand %></h3>
              <p><%= car.model %></p>
            </div>
          </div>

          <div class="car-card-price">
            <p><%= car.price.to_i %></p>
            <p class="smaller">€/day</p>
          </div>

          <div class="car-card-footer-left">
            <div class="ratings">

              <% sum_rat = car.ratings.sum(:rt_fun) + car.ratings.sum(:rt_condition) + car.ratings.sum(:rt_performance) + car.ratings.sum(:rt_owner) %>

              <% count_rat = car.ratings.count %>

              <% rat_calc = count_rat.zero? ? 0 : (sum_rat / (count_rat * 4).to_f).ceil %>

              <% if rat_calc.zero? %>
                <p><strong>New car!</strong></p>

              <% else %>
                <% (rat_calc).times do %>
                  <i class="fas fa-circle"></i>
                <% end %>
                <% (5 - rat_calc).times do %>
                  <i class="far fa-circle"></i>
                <% end %>
              <% end %>

            </div>
            <p><i class="fas fa-map-marker-alt"></i> <%= car.owner.address %></p>
          </div>

          <div class="car-card-footer-right">
            <p><i class="fas fa-industry"></i> <%= car.year %></p>
            <p><i class="fas fa-car-crash"></i> <%= number_with_delimiter(car.mileage, :delimiter => '.') %> km</p>
          </div>

          <%= link_to "", car_path(car) %>

        </div>
      </div>
  <% end %>

  </div>
</div>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>

app/views/pages/home.html.erb
  <div id="banner">
    <div class="video-wrapper">
      <%= video_tag "kittkarr.mp4", autoplay: true, loop: true, muted: true %>
          <div class="banner-content">
            <h1>Welcome to Vintage Karr</h1>
            <br>
            <p>Rent-a-Karr from the best collection of Hollywood's <br>most famous cars and vehicles in the universe!</p>

            <br>

<%= form_tag cars_path, class: "homepage-search-form", method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control home-form",
        placeholder: "Find a Karr by brand, model, owner or location"
      %>
      <%= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
        Search Karr
      <% end %>
    <% end %>

          </div>
    </div>
  </div>

<div class="text-center">
    <h2>As seen on:</h2>

    <!--Start of Press Release Jet Media Logos Code--><a href="" target="_blank" class="prj-logo prj-grayscale-false"><img src="https://pressreleasejet.com/assets/media-logos/logo-abc.png"></a><a href="" target="_blank" class="prj-logo prj-grayscale-false"><img src="https://pressreleasejet.com/assets/media-logos/logo-cbs.png"></a><a href="" target="_blank" class="prj-logo prj-grayscale-false"><img src="https://pressreleasejet.com/assets/media-logos/logo-fox.png"></a><a href="" target="_blank" class="prj-logo prj-grayscale-false"><img src="https://pressreleasejet.com/assets/media-logos/logo-nbc.png"></a><a href="" target="_blank" class="prj-logo prj-grayscale-false"><img src="https://pressreleasejet.com/assets/media-logos/logo-cw.png"></a><a href="https://pressreleasejet.com" target="_blank" class="prj-copyright" title="press release distribution">Press Release Jet</a><style type="text/css">.prj-logo img {width:auto; height:50px; opacity: 0.5; filter:alpha(opacity=50); -o-transition:.2s; -ms-transition:.2s; -moz-transition:.2s; -webkit-transition:.2s; transition:.2s;}.prj-logo img {margin-right:20px;}.prj-logo:last-of-type img {margin:0;}.prj-logo img:hover {opacity: 1.0; filter:alpha(opacity=100);}.prj-grayscale-true img {-webkit-filter: grayscale(1); filter: grayscale(1);}.prj-copyright {position:relative; left:-9999px;font-size:9px;}</style><!--End of Press Release Jet Media Logos Code-->
<br>
<br>

  </div>


  <div class="blue-bg padded">
    <div class="container text-center">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="home-card">
            <%= image_tag('karr.png') %>


            <h2>KARR</h2>
            <p>KARR is the name of a automated vehicle featured as a major antagonist of KITT</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="home-card">
            <!-- <img src="../shared/images/.svg"> -->
            <%= image_tag('kitt.png') %>
            <h2>KITT</h2>
            <p>KITT is the short name of two characters from the TV series Knight Rider</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="home-card">
            <!-- <img src="../shared/images/.svg"> -->
            <%= image_tag('bttf_delorean.png') %>
            <h2>DeLorean Time Machine</h2>
            <p>The DeLorean time machine is a automobile-based time travel vehicle</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="home-card">
            <!-- <img src="../shared/images/.svg"> -->
            <%= image_tag('batmobile.png') %>
            <h2>Batmobile</h2>
            <p>The Batmobile is a heavily armored, weaponized vehicle</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center padded newsletter">
    <h2>Subscribe to the Vintage Karr newsletter</h2>
    <p>Leave us your mail and get our latest news</p>
    <form class="form-inline">
      <input type="email" placeholder="name@email.com" class="form-control">
      <input type="submit" value="Subscribe" class="subscribe-btn btn-primary">
    </form>
  </div>

  <div id="map" style="width: 100%; height: 400px;"></div>

  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

  <script type="text/javascript">
  var myLatlng = new google.maps.LatLng(38.7260865,-9.1476757);

  var myOptions = {
    zoom: 16,
    center: myLatlng,
    scrollwheel: false,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    styles: [{"featureType":"landscape","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":51},{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"road.arterial","stylers":[{"saturation":-100},{"lightness":30},{"visibility":"on"}]},{"featureType":"road.local","stylers":[{"saturation":-100},{"lightness":40},{"visibility":"on"}]},{"featureType":"transit","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":-25},{"saturation":-100}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]}]
  };

  var map = new google.maps.Map(document.getElementById('map'), myOptions);
  var marker = new google.maps.Marker({
    position: myLatlng,
    map: map,
    title:"You are here!"
  });
  </script>
  </div>

app/views/shared/_temp.html.erb
 <div id="banner">
    <div class="video-wrapper">
      <%= video_tag "vk_landing_bkg.mp4", autoplay: true, loop: true, muted: true, style: "min-height: 100vh; min-width: 100vw;" %>
          <div class="banner-content">
            <h1>Welcome to Vintage Karr</h1>
            <br>
            <p>Rent-a-Karr from the best collection of Hollywood's <br>most famous cars and vehicles in the universe!</p>

            <br>

            <%= link_to cars_path do  %>
            <button class="btn btn-primary btn-lg">Find your KARR</button>
            <% end %>
          </div>
    </div>
  </div>